Rendering stuff
ebkalderon/amethyst pull request #3
Opened 2017-07-08 11:30 UTC by omni-viral

- Tweak `VertexFormat` trait. Adding an ability to identify kind of data an attribute belongs
- Add missing stuff to `EffectBuilder`
- Link unknown outputs in `effect::pso::Link`
- Add `Pass` variant with function that receives models
- Slice models into chunks and feed 'em to encoders
    Old mechanism draw only first `encoders.len()` models
- Add `DrawFlat` pass
- Fix issue with black textures
    by actually passing texture data on texture object creation
- Modify sphere example to render flat sphere using `DrawFlat` pass

2017-07-08 14:34 UTC, ebkalderon commented
@omni-viral Thank you for the comprehensive PR! Looks very exciting. I will review it carefully and report back to you once I'm back in the States.

2017-07-08 20:34 UTC, omni-viral commented
For no only one model could be rendered as `ClearTarget` pass get executed for each model 🦀 
It needed to slit passed into three kinds.
- `PrePass`
    All `PrePass`es will get called first by main thread
- `MainPass`
    Then `MainPass`es will get called for each model in scene in parallel with multiple encoders.
    Should different`MainPass`es draw calls be allowed to intersect? Probably not.
- `PostPass`
    And `PostPass`es will get called last by main thread

2017-07-21 16:08 UTC, ebkalderon requested changes
Wow, this is a surprisingly comprehensive pull request! I am really impressed with your work here. That said, there are some nitpicks to address, but most are fairly minor.

2017-07-21 16:08 UTC, ebkalderon commented on amethyst_renderer/src/pipe/effect/mod.rs
> +    {
This brace shouldn't be on its own line.

2017-07-21 16:08 UTC, ebkalderon commented on amethyst_renderer/src/pipe/effect/pso.rs
> +                // println!("Link constant {:?}/{:?}", info.name, cbuf);
This commented code should probably be removed before merging.

2017-07-21 16:08 UTC, ebkalderon commented on amethyst_renderer/src/pipe/effect/pso.rs
> +                    // println!("Linked {:?}", res);
This commented code should probably be removed before merging.

2017-07-21 16:08 UTC, ebkalderon commented on amethyst_renderer/src/pipe/effect/pso.rs
> +                // println!("Link global {:?}/{:?}", info.name, global);
This commented code should probably be removed before merging.

2017-07-21 16:08 UTC, ebkalderon commented on amethyst_renderer/src/pipe/effect/pso.rs
> +                    // println!("Linked {:?}", res);
This commented code should probably be removed before merging.

2017-07-21 16:08 UTC, ebkalderon commented on amethyst_renderer/src/pipe/effect/pso.rs
> +                // println!("Link output {:?}/{:?}", info.name, color);
This commented code should probably be removed before merging.

2017-07-21 16:08 UTC, ebkalderon commented on amethyst_renderer/src/pipe/effect/pso.rs
> +                // println!("Link unknown output {:?}/{:?}", info.name, color);
This commented code should probably be removed before merging.

2017-07-21 16:08 UTC, ebkalderon commented on amethyst_renderer/src/pipe/effect/pso.rs
> +            // println!("Link depth {:?}", depth);
This commented code should probably be removed before merging.

2017-07-21 16:08 UTC, ebkalderon commented on amethyst_renderer/src/pipe/effect/pso.rs
> +                // println!("Link sampler {:?}/{:?}", info, smp);
This commented code should probably be removed before merging.

2017-07-21 16:08 UTC, ebkalderon commented on amethyst_renderer/src/pipe/effect/pso.rs
> +                    // println!("Linked {:?}", d);
This commented code should probably be removed before merging.

2017-07-21 16:08 UTC, ebkalderon commented on amethyst_renderer/src/pipe/effect/pso.rs
> +                // println!("Link texture {:?}/{:?}", info, tex);
This commented code should probably be removed before merging.

2017-07-21 16:08 UTC, ebkalderon commented on amethyst_renderer/src/pipe/effect/pso.rs
> +                    // println!("Linked {:?}", res);
This commented code should probably be removed before merging.

2017-07-21 16:08 UTC, ebkalderon commented on amethyst_renderer/src/pipe/effect/pso.rs
> +            meta.vertex_bufs.push(meta_vbuf);
If this `meta_vbuf` fails to link and results in a `None`, it should not be pushed into `meta`. Please move it back to where it was, right above `desc.vertex_buffers[i] = Some(d);`.

2017-07-21 16:08 UTC, ebkalderon commented on amethyst_renderer/src/pipe/effect/pso.rs
> +            meta.textures.push(meta_tex);
If this `meta_tex` fails to link and results in a `None`, it should not be pushed into `meta`. Please move it back to where it was, right above `desc.resource_views[info.slot as usize] = Some(d);`.

2017-07-21 16:08 UTC, ebkalderon commented on amethyst_renderer/src/pipe/effect/pso.rs
> +            meta.samplers.push(meta_smp);
If this `meta_samplers` fails to link and results in a `None`, it should not be pushed into `meta`. Please move it back to where it was, right above `desc.samplers[info.slot as usize] = Some(d);`.

2017-07-21 16:08 UTC, ebkalderon commented on amethyst_renderer/src/pipe/effect/pso.rs
> +            meta.out_depth = Some(meta_depth);
If this `meta_depth` fails to link and results in a `None`, it should not be pushed into `meta`. Please move it back to where it was, right above `desc.depth_stencil = Some(d);`.

2017-07-21 16:08 UTC, ebkalderon commented on amethyst_renderer/src/pipe/effect/pso.rs
> +            meta.out_colors.push(meta_color);
If this `meta_color` fails to link and results in a `None`, it should not be pushed into `meta`. Please move it back to where it was, right above `desc.color_targets[info.slot as usize] = Some(d);`.

2017-07-21 16:08 UTC, ebkalderon commented on amethyst_renderer/src/pipe/effect/pso.rs
> +            meta.globals.push(meta_global);
If this `meta_globa` fails to link and results in a `None`, it should not be pushed into `meta`. Please move it back to where it was, right below `res.map_err(|e| InitError::GlobalConstant(info.name.as_str(), Some(e)))?;`.

2017-07-21 16:08 UTC, ebkalderon commented on amethyst_renderer/src/pipe/effect/pso.rs
> +            meta.const_bufs.push(meta_cbuf);
If this `meta_cbuf` fails to link and results in a `None`, it should not be pushed into `meta`. Please move it back to where it was, right above `desc.constant_buffers[info.slot as usize] = Some(d);`.

2017-07-21 16:08 UTC, ebkalderon commented on amethyst_renderer/src/pipe/effect/pso.rs
>                  meta.out_colors.push(meta_color);
If this `meta_color` fails to link and results in a `None`, it should not be pushed into `meta`. Please move it back to where it was, right above `desc.color_targets[info.slot as usize] = Some(d);`.

2017-07-21 16:08 UTC, ebkalderon commented on amethyst_renderer/src/scene.rs
> +/// Immutable parallel iterator of models.
Should be "Immutable chunked parallel iterator of models."

2017-07-21 16:08 UTC, ebkalderon commented on amethyst_renderer/src/pass/shaders/fragment/flat.glsl
> +
Empty line not necessary here.

2017-07-21 16:08 UTC, ebkalderon commented on amethyst_renderer/src/pass/shaders/fragment/flat.glsl
> +}
There is a missing newline at the end of this file.

2017-07-21 16:08 UTC, ebkalderon commented on amethyst_renderer/src/pass/shaders/fragment/pbm.glsl
> +}
There is a missing newline at the end of this file.

2017-07-21 16:08 UTC, ebkalderon commented on amethyst_renderer/src/pass/shaders/vertex/basic.glsl
> +}
There is a missing newline at the end of this file.

2017-07-21 16:08 UTC, ebkalderon commented on amethyst_renderer/src/pass/shaders/fragment/pbm.glsl
> +
Empty line not necessary here.

2017-07-21 16:08 UTC, ebkalderon commented on amethyst_renderer/src/pass/shaders/vertex/basic.glsl
> +
Empty line not necessary here.

2017-07-21 22:24 UTC, omni-viral commented on amethyst_renderer/src/pipe/effect/pso.rs
> +            meta.const_bufs.push(meta_cbuf);
I made this change intentionally.
If meta wouldn't pushed then all data after it will be at wrong indexes at binding phase

2017-07-21 22:25 UTC, omni-viral commented on amethyst_renderer/src/pipe/effect/pso.rs
> +            meta.globals.push(meta_global);
Same as above

2017-07-22 00:41 UTC, ebkalderon commented on amethyst_renderer/src/pipe/effect/pso.rs
> +            meta.const_bufs.push(meta_cbuf);
Oh, I was unaware that `meta` worked this way. If that's the case, then okay.

2017-07-22 20:59 UTC, omni-viral commented
I think I'm done with refactoring and changes 😄

2017-07-24 09:37 UTC, omni-viral commented on amethyst_renderer/src/pipe/effect/pso.rs
> +            meta.out_colors.push(meta_color);
same

2017-07-24 09:37 UTC, omni-viral commented on amethyst_renderer/src/pipe/effect/pso.rs
>                  meta.out_colors.push(meta_color);
same

2017-07-24 09:37 UTC, omni-viral commented on amethyst_renderer/src/pipe/effect/pso.rs
> +            meta.samplers.push(meta_smp);
same

2017-07-24 09:37 UTC, omni-viral commented on amethyst_renderer/src/pipe/effect/pso.rs
> +            meta.textures.push(meta_tex);
same

2017-07-24 09:38 UTC, omni-viral commented on amethyst_renderer/src/pipe/effect/pso.rs
> +            meta.vertex_bufs.push(meta_vbuf);
same

2017-07-24 09:38 UTC, omni-viral commented on amethyst_renderer/src/pass/shaders/fragment/flat.glsl
> +
moved

2017-07-24 09:38 UTC, omni-viral commented on amethyst_renderer/src/pass/shaders/fragment/flat.glsl
> +}
Added

2017-07-24 09:38 UTC, omni-viral commented on amethyst_renderer/src/pass/shaders/fragment/pbm.glsl
> +
Moved

2017-07-24 09:38 UTC, omni-viral commented on amethyst_renderer/src/pass/shaders/fragment/pbm.glsl
> +}
Added

2017-07-24 09:38 UTC, omni-viral commented on amethyst_renderer/src/pass/shaders/vertex/basic.glsl
> +
Moved

2017-07-24 09:39 UTC, omni-viral commented on amethyst_renderer/src/pass/shaders/vertex/basic.glsl
> +}
Added

2017-07-24 13:10 UTC, ebkalderon approved these changes

2017-07-24 13:11 UTC, ebkalderon commented
@omni-viral Looks pretty good to me. Thank you for addressing pretty much all my concerns, and I appreciate all your hard work! 🎉

2017-07-24 13:11 UTC, merged